# Generated by Django 5.1.4 on 2026-06-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('jd_text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('fit_score', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='job_finder.resume')),
            ],
            options={
                'ordering': ['-fit_score'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('wants_remote', models.BooleanField(default=False)),
                ('skills', models.JSONField(default=list)),
                ('titles', models.JSONField(default=list)),
                ('years_experience', models.FloatField(blank=True, null=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='job_finder.resume')),
            ],
        ),
        migrations.CreateModel(
            name='TailoredResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('job_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailored', to='job_finder.jobmatch')),
            ],
        ),
    ]
