# Generated by Django 5.1.4 on 2026-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='wants_remote',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
