# Generated by Django 5.1.4 on 2026-06-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0002_remove_candidateprofile_wants_remote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmatch',
            options={'ordering': ['tier', '-fit_score']},
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='country',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='tier',
            field=models.IntegerField(default=4),
        ),
    ]
