# Generated by Django 5.1.4 on 2026-06-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0003_alter_jobmatch_options_jobmatch_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmatch',
            options={'ordering': ['-fit_score']},
        ),
    ]
