# Generated by Django 5.1.4 on 2026-06-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0004_alter_jobmatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
