# Generated by Django 5.1.4 on 2026-06-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_finder', '0005_candidateprofile_github_candidateprofile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
